---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by perr.
--- DateTime: 9/23/2026 AD 01:40
---

local htmlkit = require('@htmlkit')
local code_block = require('component/code-block')

local data = {}

data.name = "Installation"

function data.render()
    local view = htmlkit.el("div"):class("max-w-3xl"):child(
            htmlkit.el("h1"):class("text-3xl font-bold text-olive-950 mb-3"):text("Installation"),
            htmlkit.el("p"):class("text-olive-800 leading-relaxed"):text("getting zolt running is really easy all you need is terminal."),
            code_block.render("curl -fsSL https://zolt-doc.perr.dev/public/install-zolt.sh | bash", "terminal"),
            htmlkit.el("p"):class("text-olive-800 leading-relaxed"):text("after that restart your shell (or run source ~/.zshrc / source ~/.bashrc)"),
            htmlkit.el("h2"):class("text-xl font-semibold text-olive-950 mt-8 mb-2"):text("Build from source"),
            htmlkit.el("p"):class("text-olive-800 leading-relaxed"):text("want to build it yourself? you'll need go."),
            code_block.render("git clone https://github.com/iluvicecream/zolt\ncd zolt\ngo run main.go", "terminal"),
            htmlkit.el("div"):class("mt-6"):child(
                htmlkit.el("a"):text("Next"):attr("href", "index.lua?slug=get-started/getting-started"):class("inline-block bg-olive-700 text-olive-50 px-4 py-2 rounded-lg hover:bg-olive-800")
            )
    )
    return view
end

return data
