---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by perr.
--- DateTime: 9/23/2026 AD 01:10
---

local data = { }

data.sidebar = {
    {
        name='Get Started',
        items = {
            {
                name = 'Installation',
                slug = 'get-started/installation'
            },
            {
                name = 'Getting Started',
                slug = 'get-started/getting-started'
            }
        }
    },
    {
        name = 'Runtime',
        items = {
            {
                name = 'Output',
                slug = 'runtime/output'
            },
            {
                name = 'Request',
                slug = 'runtime/request'
            },
            {
                name = 'Set Status',
                slug = 'runtime/set-status'
            },
            {
                name = 'Content Type',
                slug = 'runtime/content-type'
            },
            {
                name = 'Header Add',
                slug = 'runtime/header-add'
            }
        }
    },
    {
        name = 'Modules',
        items = {
            {
                name = '@htmlkit',
                slug = 'runtime/htmlkit'
            },
            {
                name = '@turbokit',
                slug = 'runtime/turbokit'
            },
            {
                name = '@version',
                slug = 'runtime/version'
            }
        }
    }
}

return data;
