---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by perr.
--- DateTime: 9/23/2026 AD 01:10
---

local data = { }

data.sidebar = {
    {
        name='Get Started',
        items = {
            {
                name = 'Installation',
                path = '/get-started/installation'
            }
        }
    }
}

return data;