---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by perr.
--- DateTime: 9/23/2026 AD 16:23
---
local htmlkit = require("@htmlkit")
local code_block = require('component/code-block')

local data = {}

data.name = "Welcome"

function data.render()
    local view = htmlkit.el("div"):child(
            htmlkit.el("h1"):class("text-4xl font-bold text-olive-950 mb-4"):text("Zolt"),
            htmlkit.el("p"):class("text-lg text-olive-800 leading-relaxed max-w-3xl"):text("a tiny go web server that speaks your language. you write your pages in lua and zolt runs them for you and return it to your user. no build step, no framework, no fuss."),
            code_block.render("echo(\"Hello, world!\")"),
            htmlkit.el("div"):class("mt-6"):child(
                htmlkit.el("a"):text("Let Go!"):attr("href", "index.lua?slug=get-started/installation"):class("inline-block bg-olive-700 text-olive-50 px-4 py-2 rounded-lg hover:bg-olive-800")
            )
    )
    return view
end

return data
