---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by perr.
--- DateTime: 9/23/2026 AD 16:17
---
local htmlkit = require('@htmlkit')

local M = {}

function M.render(slug)
    local data = require('shared/doc/' .. slug)
    local content = htmlkit.el('div'):child(
        data.render()
    )

    return content
end

return M
