---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by perr.
--- DateTime: 9/23/2026 AD 01:14
---
local M = {}

local data = require('shared/data')
local htmlkit = require('@htmlkit')

function M.render_sidebar()
    local groups = {}
    for _ , group in ipairs(data.sidebar) do
        items_obj = {}
        for _ , items in ipairs(group.items) do
            local item = htmlkit.el("a"):text(items.name):attr('href',items.path)
            table.insert(items_obj,item);
        end
        local group = htmlkit.el("div"):child(
                htmlkit.el("h1"):text(group.name),
                htmlkit.el("div"):child(unpack(items_obj))
        )
        table.insert(groups,group);
    end

    local sidebar = htmlkit.el("div"):child(unpack(groups))
    return sidebar
end

return M